#!/usr/bin/env python3
"""
SessionStart(source=compact) hook — a bypass path around the compactor.

Compaction is a polarizer whose basis is narrative coherence. Content
aligned with narrative passes through the summary; content orthogonal to it
is absorbed — verbatim rulings, exact SHAs, file paths, process handles.
This hook re-reads the on-disk transcript (which never went through the
compactor) and recombines: the summary is the coherent, narrative-aligned
component, this block is the cross-polarized one.

Selection rule: carry what the summary is likely to have flattened. Never
duplicate what a summary preserves well (arc, motivation, conclusions).

Coherence rule: the ledger (disk) is authoritative, the summary is derived.
This block says so explicitly so the resumed session adopts the right
posture toward the two.

Design note: PreCompact cannot inject context — its only channel is
block/no-block — and it isn't needed here: everything of value is durable
on disk at read time. SessionStart(source=compact) is the documented
re-injection point and its stdout is delivered directly.

Safety contract: never raises, always exits 0, degrades to silence.
Output is bounded (~6KB) since it is injected on every compaction.

Portability: repo-freshness checks and the in-flight scratch-dir scan are
best-effort and skip cleanly when the paths they look for don't exist —
nothing here requires the cog workspace or a particular repo layout.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

MAX_OPERATOR_MSGS = 14
MAX_MSG_CHARS = 400
MAX_TOTAL = 6000

NOISE_MARKERS = (
    "<system-reminder>",
    "<local-command-",
    "[SYSTEM NOTIFICATION",
    "<task-notification>",
    "<cogos_subagent_identity>",
    "Caveat: The messages below were generated by the user",
)


def _text_of(rec: dict) -> str:
    msg = rec.get("message") or {}
    c = msg.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return "\n".join(
            b.get("text", "") for b in c if isinstance(b, dict) and b.get("type") == "text"
        )
    return ""


def operator_verbatim(transcript: Path) -> list[str]:
    """The highest-value cross-polarized content: the operator's exact words.

    Summaries paraphrase rulings, and a paraphrased ruling is a different
    ruling. These are copied byte-exact.
    """
    out: list[str] = []
    try:
        with transcript.open() as f:
            for line in f:
                try:
                    rec = json.loads(line)
                except Exception:
                    continue
                if rec.get("type") != "user":
                    continue
                t = _text_of(rec).strip()
                if not t or any(m in t for m in NOISE_MARKERS):
                    continue
                out.append(t)
    except OSError:
        return []
    return out[-MAX_OPERATOR_MSGS:]


def _scratch_bases() -> list[Path]:
    """Claude Code's own per-session scratch roots. Layout is
    <tmp_root>/claude-<uid>/<mangled-cwd>/ on this harness; glob for it
    generically instead of hardcoding a uid or a specific mangled path so
    this works on any machine/user, not just the one this hook was
    authored on."""
    tmp_root = Path(os.environ.get("TMPDIR") or "/private/tmp")
    bases: list[Path] = []
    try:
        for claude_dir in tmp_root.glob("claude-*"):
            if not claude_dir.is_dir():
                continue
            bases.extend(p for p in claude_dir.iterdir() if p.is_dir())
    except Exception:
        pass
    return bases


def in_flight(session_id: str) -> list[str]:
    """Process state the narrative absorbs: what was still running."""
    rows: list[str] = []
    try:
        for base in _scratch_bases():
            for sess in base.glob(f"{session_id}*/tasks"):
                for out in sorted(sess.glob("*.output"), key=lambda p: -p.stat().st_mtime)[:6]:
                    try:
                        lines = [l for l in out.read_text(errors="replace").splitlines() if l.strip()]
                    except Exception:
                        continue
                    if not lines:
                        continue
                    tail = lines[-1]
                    # Agent .output files are full JSONL transcripts, not
                    # task output — their tail is a raw record, useless here.
                    if tail.lstrip().startswith("{"):
                        continue
                    rows.append(f"{out.stem}: {tail[:90]}")
    except Exception:
        pass
    return rows


def uncommitted() -> list[str]:
    """Work that hadn't reached a fixed point. The horizon takes exactly this.

    Repo set is env-driven per the standing path convention (COGOS_WORKSPACE,
    MYRGIC_REPOS_ROOT) so this generalizes past one operator's layout; repos
    that don't exist on a given machine are silently skipped.
    """
    cogos_ws = Path(os.environ.get("COGOS_WORKSPACE", str(Path.home() / "workspaces" / "cog")))
    myrgic_root = Path(os.environ.get("MYRGIC_REPOS_ROOT", str(Path.home() / "workspaces" / "myrgic")))
    repos = [
        cogos_ws,
        myrgic_root / "cogos",
        Path.home() / ".hermes" / "hermes-agent",
    ]
    rows: list[str] = []
    for r in repos:
        if not (r / ".git").exists():
            continue
        try:
            p = subprocess.run(
                ["git", "-C", str(r), "status", "--short"],
                capture_output=True, text=True, timeout=5,
            )
            n = len([l for l in p.stdout.splitlines() if l.strip()])
            if n:
                head = subprocess.run(
                    ["git", "-C", str(r), "log", "-1", "--format=%h %s"],
                    capture_output=True, text=True, timeout=5,
                ).stdout.strip()[:70]
                rows.append(f"{r.name}: {n} uncommitted · head {head}")
        except Exception:
            continue
    return rows


def main() -> None:
    try:
        raw = sys.stdin.read()
        payload = json.loads(raw) if raw.strip() else {}
    except Exception:
        payload = {}

    if payload.get("source") not in (None, "compact"):
        sys.exit(0)

    transcript = payload.get("transcript_path")
    session_id = (payload.get("session_id") or "")[:36]

    parts: list[str] = [
        "<compaction_handoff>",
        "The summary above is an INDEX; the items below are the RECORD — the "
        "cross-polarized component the summarizer is misaligned with "
        "(verbatim wording, process handles, unsettled work). Trust these "
        "over any paraphrase of them.",
    ]

    if transcript:
        msgs = operator_verbatim(Path(transcript))
        if msgs:
            parts.append("\n## Operator, verbatim (most recent, exact)")
            for m in msgs:
                one = " ".join(m.split())
                parts.append(f'- "{one[:MAX_MSG_CHARS]}"')

    if session_id:
        rows = in_flight(session_id)
        if rows:
            parts.append("\n## Background tasks (last line of each — may be stale)")
            parts.extend(f"- {r}" for r in rows)

    rows = uncommitted()
    if rows:
        parts.append("\n## Uncommitted (the horizon takes what hasn't settled)")
        parts.extend(f"- {r}" for r in rows)

    if transcript:
        parts.append(f"\nFull transcript (authoritative): {transcript}")
    parts.append("</compaction_handoff>")

    out = "\n".join(parts)
    if len(out) > MAX_TOTAL:
        out = out[: MAX_TOTAL - 30] + "\n…truncated\n</compaction_handoff>"
    print(out)
    sys.exit(0)


if __name__ == "__main__":
    main()
